export const WS_EVENTS = {
  GET_ROOMS: 'get_rooms',
  GET_MESSAGES: 'get_messages',
  CREATE_MESSAGE: 'create_message',
  MARK_ROOM_READ: 'mark_room_read',
  GET_UNREAD_COUNT: 'get_unread_count',
  GET_ALL_ONLINE_USERS: 'get_all_online_users',
  JOIN_ROOM: 'join_room',
  USER_OFFLINE: 'user_offline',
  CLOSE_SUPPORT_ROOM: 'close_support_room',
  GET_ROOM_ONLINE_MEMBERS: 'get_room_online_members',
  USER_REQUEST_SUPPORT: 'user_request_support',
  ADMIN_JOIN_SUPPORT_ROOM: 'admin_join_support_room',
  GET_PENDING_SUPPORT_ROOMS: 'get_pending_support_rooms',
  CLIENT_LEAVE_ROOM: 'client_leave_room',
  CLIENT_DELETE_ROOM: 'client_delete_room',
} as const;

export const WS_RESPONSE_EVENTS = {
  ERROR: 'error',
  AUTH_ERROR: 'auth_error',
  CONNECTION_SUCCESS: 'connection_success',
  ROOMS: 'rooms',
  MESSAGES: 'messages',
  MARK_ROOM_READ_SUCCESS: 'mark_room_read_success',
  ROOM_MARKED_READ: 'room_marked_read',
  UNREAD_COUNT: 'unread_count',
  UNREAD_COUNT_UPDATED: 'unread_count_updated',
  MESSAGE_CREATED: 'message_created',
  NEW_MESSAGE: 'new_message',
  ROOM_JOINED: 'room_joined',
  USER_ONLINE: 'user_online',
  USER_OFFLINE: 'user_offline',
  ALL_ONLINE_USERS: 'all_online_users',
  SUPPORT_ROOM_CLOSED: 'support_room_closed',
  SUPPORT_ADMIN_CHANGED: 'support_admin_changed',
  SUPPORT_ROOM_PENDING: 'support_room_pending',
  SUPPORT_ROOM_ASSIGNED: 'support_room_assigned',
  SUPPORT_ADMIN_JOINED: 'support_admin_joined',
  SUPPORT_TICKET_ASSIGNED: 'support_ticket_assigned',
  PENDING_SUPPORT_ROOMS: 'pending_support_rooms',
  ROOM_ONLINE_MEMBERS: 'room_online_members',
  ROOM_DELETED: 'room_deleted',
  ROOM_LEFT: 'room_left',
} as const;
